version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5005:5005"
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=expensesdb
      - DB_PASSWORD=FergLib2024!
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FergLib2024!
      POSTGRES_DB: expensesdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

